apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: redis-caching-agent
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
        - image: gcr.io/agent-factory-474201/redis-caching-agent:latest
          ports:
          - containerPort: 8080
          env:
          - name: REDIS_HOST
            value: "10.1.93.195"
          - name: REDIS_PORT
            value: "6379"
          - name: REDIS_URL
            value: "redis://10.1.93.195:6379"
          - name: ENVIRONMENT
            value: "production"
          - name: PORT
            value: "8080"
          resources:
            limits:
              cpu: "2"
              memory: "2Gi"
            requests:
              cpu: "1"
              memory: "1Gi"
